opt_in_rules:
  - alternative_names
  - attributes
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - control_statement
  - discouraged_direct_init
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - discouraged_optional_string
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_string
  - file_length
  - force_cast
  - force_try
  - generic_type_name
  - identifier_name
  - implicit_return
  - large_tuple
  - legacy_constant
  - legacy_multiple
  - line_length
  - mark
  - multiline_arguments_brackets
  - multiline_arguments_indentation
  - multiline_function_chains
  - multiline_function_declaration
  - multiline_function_parameters
  - multiline_parameters
  - multiline_parameters_brackets
  - multiline_parameters_end_indentation
  - multiline_parameters_trailing_comma
  - multiline_parameters_where_clause
  - multiline_return
  - multiline_string_literals
  - multiline_trailing_comma
  - nested_code_block_depth
  - nesting
  - number_separator
  - operator_usage_whitespace
  - opening_brace
  - operator_whitespace
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_void_return
  - return_arrow_whitespace
  - return_count
  - sorted_imports
  - statement_position
  - superfluous_disable_command
  - todo
  - type_body_length
  - type_contents_order
  - type_name
  - unneeded_break_in_switch
  - unneeded_enum_case_value
  - unneeded_parentheses_in_closure_argument
  - unneeded_parentheses_in_optional_return
  - valid_docs
  - vertical_parameter_alignment
  - vertical_whitespace

excluded:
  - Carthage
  - Pods

disabled_rules:
  - trailing_whitespace

